    let a=5;
    let b=10;
    let c=a+b;
    console.log('The sum of ' + a + ' and ' + b + ' is ' + c);
    let d=a-b;
    console.log('The difference of ' + a + ' and ' + b + ' is ' + d);
    let e=a*b;
    console.log('The product of ' + a + ' and ' + b + ' is ' + e);  
    let f=a/b;
    console.log('The quotient of ' + a + ' and ' + b + ' is ' + f);
    let g=a%b;
    console.log('The remainder of ' + a + ' divided by ' + b + ' is ' + g);